paths:
  /v1/listen:
    post:
      x-fern-sdk-group-name:
        - speechToText
      x-fern-sdk-method-name: listen
      x-fern-examples: 
        - code-samples: 
            - language: java
              code: |-
                import com.deepgram.api.Deepgram;

                Deepgram deepgram = Deepgram.builder()
                  .apiKey("YOUR_API_KEY")
                  .build();

                deepgram.speechToText.listen(Event.builder()
                    .url("https://dpgr.am/spacewalk.wav")
                    .build());
  /v1/projects:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: list
  /v1/projects/{project_id}:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: update
  /v1/projects/{project_id}/balances:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: listBalances
  /v1/projects/{project_id}/balances/{balance_id}:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: getBalance
  /v1/projects/{project_id}/models:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: listModels
  /v1/projects/{project_id}/models/{model_id}:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: getModel
  /v1/projects/{project_id}/keys:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: listKeys
  /v1/projects/{project_id}/keys/{key_id}/keys:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: getKey
    delete:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: deleteKey
  /v1/projects/{project_id}/members:
    get:
      x-fern-sdk-group-name: 
        - projects
        - members
      x-fern-sdk-method-name: list
  /v1/projects/{project_id}/members/{member_id}:
    delete:
      x-fern-sdk-group-name: 
        - projects
        - members
      x-fern-sdk-method-name: get
  /v1/projects/{project_id}/members/{member_id}/scopes:
    get:
      x-fern-sdk-group-name: 
        - projects
        - members
      x-fern-sdk-method-name: listScopes
    put:
      x-fern-sdk-group-name: 
        - projects
        - members
      x-fern-sdk-method-name: updateScopes
  /v1/projects/{project_id}/invites:
    get:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: listInvites
    post:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: createInvite
  /v1/projects/{project_id}/invites/{email}:
    delete:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: deleteInvite
  /v1/projects/{project_id}/leave:
    delete:
      x-fern-sdk-group-name: 
        - projects
      x-fern-sdk-method-name: leave
