paths:
  /v1/listen:
    post:
      x-fern-sdk-group-name:
        - speechToText
      x-fern-sdk-method-name: listen
  /v1/read:
    post:
      x-fern-sdk-group-name:
        - textIntelligence
      x-fern-sdk-method-name: TextRead
  /v1/speak:
    post:
      x-fern-sdk-group-name:
        - textToSpeech
      x-fern-sdk-method-name: speak
  /v1/projects:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: list
  /v1/projects/{project_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: update
  /v1/projects/{project_id}/balances:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - balances
      x-fern-sdk-method-name: list
  /v1/projects/{project_id}/balances/{balance_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - balances
      x-fern-sdk-method-name: get
  /v1/projects/{project_id}/models:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: listModels
  /v1/projects/{project_id}/models/{model_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - projects
      x-fern-sdk-method-name: getModel
  /v1/projects/{project_id}/keys:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - keys
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - managementApi
        - keys
      x-fern-sdk-method-name: create
  /v1/projects/{project_id}/keys/{key_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - keys
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - managementApi
        - keys
      x-fern-sdk-method-name: delete
  /v1/projects/{project_id}/members:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - members
      x-fern-sdk-method-name: list
  /v1/projects/{project_id}/members/{member_id}:
    delete:
      x-fern-sdk-group-name:
        - managementApi
        - members
      x-fern-sdk-method-name: delete
  /v1/projects/{project_id}/members/{member_id}/scopes:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - scopes
      x-fern-sdk-method-name: list
    put:
      x-fern-sdk-group-name:
        - managementApi
        - scopes
      x-fern-sdk-method-name: update
  /v1/projects/{project_id}/invites:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - invitations
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - managementApi
        - invitations
      x-fern-sdk-method-name: create
  /v1/projects/{project_id}/invites/{email}:
    delete:
      x-fern-sdk-group-name:
        - managementApi
        - invitations
      x-fern-sdk-method-name: delete
  /v1/projects/{project_id}/leave:
    delete:
      x-fern-sdk-group-name:
        - managementApi
        - invitations
      x-fern-sdk-method-name: leave
  /v1/projects/{project_id}/requests:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - usage
      x-fern-sdk-method-name: listRequests
  /v1/projects/{project_id}/requests/{request_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - usage
      x-fern-sdk-method-name: getRequest
  /v1/projects/{project_id}/usage:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - usage
      x-fern-sdk-method-name: get
  /v1/projects/{project_id}/usage/fields:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - usage
      x-fern-sdk-method-name: listFields
  /v1/projects/{project_id}/usage/breakdown:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - usage
      x-fern-sdk-method-name: getBreakdown
  /v1/projects/{project_id}/purchases:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - purchases
      x-fern-sdk-method-name: list
  /v1/models:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - models
      x-fern-sdk-method-name: list
  /v1/models/{model_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
        - models
      x-fern-sdk-method-name: get
  /v1/projects/{project_id}/self-hosted/distribution/credentials:
    get:
      x-fern-sdk-group-name:
        - selfHostedApi
      x-fern-sdk-method-name: listCredentials
    post:
      x-fern-sdk-group-name:
        - selfHostedApi
      x-fern-sdk-method-name: createCredentials
  /v1/projects/{project_id}/self-hosted/distribution/credentials/{distribution_credentials_id}:
    get:
      x-fern-sdk-group-name:
        - selfHostedApi
      x-fern-sdk-method-name: getCredentials
    delete:
      x-fern-sdk-group-name:
        - selfHostedApi
      x-fern-sdk-method-name: deleteCredentials
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      x-fern-header:
        prefix: Token
