paths:
  /v1/listen:
    post:
      x-fern-sdk-group-name:
        - speechToText
      x-fern-sdk-method-name: listen
  /v1/read:
    post:
      x-fern-sdk-group-name:
        - textIntelligence
      x-fern-sdk-method-name: TextRead
  /v1/speak:
    post:
      x-fern-sdk-group-name:
        - textToSpeech
      x-fern-sdk-method-name: speak
  /v1/projects:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjects
  /v1/projects/{project_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProject
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteProject
    patch:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: updateProject
  /v1/projects/{project_id}/balances:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectBalances
  /v1/projects/{project_id}/balances/{balance_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectBalance
  /v1/projects/{project_id}/models:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectModels
  /v1/projects/{project_id}/models/{model_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectModel
  /v1/projects/{project_id}/keys:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectKeys
    post:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: createProjectKey
  /v1/projects/{project_id}/keys/{key_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectKey
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteProjectKey
  /v1/projects/{project_id}/members:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectMembers
  /v1/projects/{project_id}/members/{member_id}:
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteProjectMember
  /v1/projects/{project_id}/members/{member_id}/scopes:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectMemberScopes
    put:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: updateProjectMemberScopes
  /v1/projects/{project_id}/invites:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectInvites
    post:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: createProjectInvite
  /v1/projects/{project_id}/invites/{email}:
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteProjectInvite
  /v1/projects/{project_id}/leave:
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteProjectLeave
  /v1/projects/{project_id}/requests:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectRequests
  /v1/projects/{project_id}/requests/{request_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectRequest
  /v1/projects/{project_id}/usage:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectUsage
  /v1/projects/{project_id}/usage/fields:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectUsageFields
  /v1/projects/{project_id}/usage/breakdown:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getProjectUsageBreakdown
  /v1/projects/{project_id}/purchases:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listProjectPurchases
  /v1/models:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listModels
  /v1/models/{model_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getModel
  /v1/projects/{project_id}/self-hosted/distribution/credentials:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: listSelfHostedDistCreds
    post:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: createSelfHostedDistCreds
  /v1/projects/{project_id}/self-hosted/distribution/credentials/{distribution_credentials_id}:
    get:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: getSelfHostedCredentials
    delete:
      x-fern-sdk-group-name:
        - managementApi
      x-fern-sdk-method-name: deleteSelfHostedDistCreds
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      x-fern-header: 
        prefix: Token
  schemas:
    speak_request: 
      type: object
      properties:
        text:
          type: string
          description: The text to speak