#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Define the directory path
const dirPath = path.join(__dirname, '../fern/docs');

// Check if the directory exists
if (!fs.existsSync(dirPath)) {
    console.error('Error: ../fern/docs directory does not exist');
    process.exit(1);
}

// Remove all contents of the directory
fs.readdir(dirPath, (err, files) => {
    if (err) throw err;

    for (const file of files) {
        fs.unlink(path.join(dirPath, file), err => {
            if (err) throw err;
        });
    }

    console.log('Successfully cleared contents of ../fern/docs directory');
});
