name: Remote Change Preview
description: Preview any changes triggered from a remote repository

on:
  repository_dispatch:
    types: [preview-docs]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm i

      - name: Setup project
        run: npm run prepreview

      - name: Generate preview output
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          OUTPUT=$(npx fern generate --docs --preview 2>&1) || true
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
          echo "Preview URL: $URL"
          echo "🌿 Preview your docs: $URL" > output.txt
          echo '' >> output.txt
          echo '<details>' >> output.txt
          echo '<summary>Build Logs</summary>' >> output.txt
          echo '```' >> output.txt
          echo "$OUTPUT" >> output.txt
          echo '```' >> output.txt
          echo '</details>' >> output.txt

      - name: Return preview output to triggering repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.repository }}
          event-type: preview-docs-response
          client-payload: '{"output": "$(cat output.txt)"}'
