name: Release Java SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the Java SDK that you would like to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Setup pnpm with cache
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Download Fern
        run: pnpm add -g fern-api

      - name: Release SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          fern generate --group java-sdk --version ${{ inputs.version }} --log-level debug --api openapi
