name: Lint

on:
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**.md'
      - '**.mdx'
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.js'
      - '**.md'
      - '**.mdx'
      - '**.yml'
      - '**.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm with cache
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm run format:check

      - name: Lint code
        run: pnpm run lint
