name: Preview Docs

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup pnpm with cache
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Install Fern
        run: pnpm add -g fern-api

      - name: Generate preview output
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          OUTPUT=$(fern generate --docs --preview 2>&1) || true
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
          echo "Preview URL: $URL"
          echo "🌿 Preview your docs: $URL" > output.txt
          echo '' >> output.txt
          echo '<details>' >> output.txt
          echo '' >> output.txt
          echo '<summary>Build Logs</summary>' >> output.txt
          echo '' >> output.txt
          echo '```' >> output.txt
          echo '' >> output.txt
          echo "$OUTPUT" >> output.txt
          echo '' >> output.txt
          echo '```' >> output.txt
          echo '' >> output.txt
          echo '</details>' >> output.txt

      - name: Comment on the PR
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          filePath: output.txt
