name: Publish Docs

on:
  push:
    branches:
      - fern/deepgram-ai

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Fern
        run: npm install -g fern-api

      - name: Install custom component dependencies
        run: npm --prefix custom-app install

      - name: Build the custom components
        run: npm --prefix custom-app run build

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          GTM_CONTAINER_ID: ${{ secrets.GTM_CONTAINER_ID }}
        run: fern generate --docs
